version: "3.3"
services:
  web:
    env_file:
      - .env
    container_name: tubes-1-letterpaw
    build: .
    image: tubes-1:latest
    command: --default-authentification-plugin=mysql_native_password
    depends_on:
      - php-db
    ports:
      - 8008:80
    environment:
      - MYSQL_ROOT_PASSWORD=${password}
      - MYSQL_DATABASE=mysql_database
      - MYSQL_USER=${nama}
      - MYSQL_PASSWORD=${password}
      - USE_DOCKER_CONFIG=true
      - DB_HOST=php-db
    volumes:
      - .:/var/www/html/
  php-db:
    env_file:
      - .env
    container_name: tubes-1-database
    image: mysql:latest
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${password}
      - MYSQL_DATABASE=mysql_database
      - MYSQL_USER=${nama}
      - MYSQL_PASSWORD=${password}
      - USE_DOCKER_CONFIG=true
    ports:
      - "9907:3307"
    volumes:
      - ./script/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql 
  phpmyadmin:
    container_name: tubes-1-phpmyadmin
    image: phpmyadmin/phpmyadmin
    depends_on:
      - php-db
    environment:
      PMA_HOST: php-db
    restart: unless-stopped
    ports:
      - "8088:80"